version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      - "POSTGRES_DB=texts"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=12345"
      - "PGDATA=/var/lib/postgresql/data/nhl-backporting"
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    shm_size: 512mb
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - texts_network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - texts_network

networks:
  texts_network:
    driver: bridge

volumes:
  pg_data: